spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    gateway:
      routes:
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/resources/**
        - id: song-service
          uri: lb://song-service
          predicates:
            - Path=/songs/**
        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/storages/**
        - id: resource-service-actuator
          uri: lb://resource-service
          predicates:
            - Path=/management/resource-service/**
          filters:
            - StripPrefix=2
        - id: song-service-actuator
          uri: lb://song-service
          predicates:
            - Path=/management/song-service/**
          filters:
            - StripPrefix=2

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411}/api/v2/spans
