spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/resources/**
        - id: song-service
          uri: lb://song-service
          predicates:
            - Path=/songs/**
        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/storages/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
