apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    uid: elasticsearch
    url: http://elasticsearch:9200
    access: proxy
    jsonData:
      index: "mp3tracker-logs-*"
      timeField: "@timestamp"
      logMessageField: message
      logLevelField: level
      esVersion: "7.10.0"
      maxConcurrentShardRequests: 5
      interval: Daily
