input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if ![service] {
    mutate {
      add_field => { "service" => "unknown" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["${ELASTICSEARCH_URL}"]
    index => "mp3tracker-logs-%{+YYYY.MM.dd}"
  }
}
