spring:
  application:
    name: config-server
  profiles:
    active: native
    group:
      local: "native"
  cloud:
    config:
      server:
        native:
          search-locations: file:///config-repo

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411}/api/v2/spans
