spring:
  application:
    name: resource-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5442/resource_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

aws:
  s3:
    endpoint: ${AWS_S3_ENDPOINT:http://localhost:4566}
    bucket-name: ${AWS_S3_BUCKET_NAME:mp3-resources}
    region: ${AWS_S3_REGION:us-east-1}
    access-key: ${AWS_ACCESS_KEY_ID:test}
    secret-key: ${AWS_SECRET_ACCESS_KEY:test}
